lab9/urls.py
from django.urls import path
from django.contrib import admin
from . import views 
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import *


app_name = 'lab9'

urlpatterns = [
	path('searchbook', views.searchbook, name="home"),
	path('searchJson', views.searchJson, name="searchJson"),
        path('increasefav', views.increasefav, name='increasefav'),
	path('decreasefav', views.decreasefav, name='decreasefav'),
	path('logout', views.logout_view , name='logout'),

]

labppw/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab9.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', include('social_django.urls', namespace='social'))
]

lab9/models.py
from django.db import models

lab9/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
import requests
import json

# Create your views here.
def searchbook(request):
    if request.user.is_authenticated:
        request.session['user'] = request.user.username
        request.session['email'] = request.user.email
        count = request.session.get('counter', 0)
        request.session['counter'] = count + 1
        for key, value in request.session.items():
            print('{} = {}'.format(key, value))
    return render(request, 'searchbook.html')


def searchJson(request):
	searching =  request.GET.get('cari')	
	url = "https://www.googleapis.com/books/v1/volumes?q=" + searching
	data = requests.get(url).json()
	if request.user.is_authenticated:
		count = request.session.get('counter',0)
		request.session['counter'] = count
		for key, value in request.session.items():
			print('{} => {}'.format(key,value))
	return JsonResponse(data)

    
def logout_view(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/searchbook')

def increasefav(request):
	print(dict(request.session))
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type='application/json')

def decreasefav(request):
	#print(dict(request.session))
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type='application/json')

lab9/templates/searchbook.html
<!DOCTYPE html>
<html>
<head>
	{%load static%}
	<title>List of Books</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<script src="{% static 'searchbook.js' %}"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
	<style type="text/css">
		body {
			background: linear-gradient(to bottom,  #ffcc00 0%, #ff99cc 100%);
		}
		.btn {
			background-color: black;
		}
	</style>

</head>
<body>
	<div class="container">
		<div class="row" style="margin-top: 3%">
	        {%if user.is_authenticated%}
	        <header class = "m-3" ">
	        	<a href= "{% url 'lab9:logout'%}" style="text-transform:none; margin-top: 3%;">
         			<div class="left">
             			<img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         			</div>
         			Log Out
         		</a>
	            <h3>Hello, {{ user.username }}!</h3>
	        </header>
	        {%else%}<header>
	        	<a href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
         			<div class="left">
             			<img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
         			</div>
         		Login with Google
         	</a>
         	<br>
	        </header>
	        {%endif%}
		</div>
		<div row>
			<div class="text-center">
				<input type=text id="searchbar" class="textbox" style="margin-bottom: 2%;"> 
				<br>
				<h1>List Of Books</h1>
				<h2>Favourite your Books Here!</h2>
				<button class="btn btn-dark" id="caribtn" onclick="cari()">Search</button>
			</div>

	    	<div class="col-sm-12">
	    		<h4 id="fav"><i class='fa fa-star'style = 'color : #DA70D6'></i> {{ count }} </h4>
	    	</div>
	    	<div class="table-responsive">          
    	  	<table class="table" id="result" style="">
    		</table>
</div>
</body>
</html>